### ISSUE TITLE
Fetching Data from API is not working

### ISSUE THREAD

**Issue by MikoDevelop** [bgildson/flutter_tinder_template#1]
There is API which the app is getting data from but it cant display the data.  Thanks in advance.

**Comment by MikoDevelop** [comment]
finally ... the api work just fine but the problem was user_services.dart file in line 55 , which convert the age by getting the date of birth from the api. for now just give it a number like 22 and it will work by assigning everyone age 22.

**Comment by MikoDevelop** [comment]
> There is API which the app is getting data from but it cant display the data. Thanks in advance.

**Comment by bgildson** [comment]
Hey, thank you for report this.
I think that is ok now, if another question/problem happen, notify me again.
